config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  resources :cart

  resources :products do
    member do
      resource :cart, only: [:update] do
        [:add, :remove, :update].each do |action|
          patch action, to: "cart#update", as: "#{action}_products_to", defaults: { action_type: action.to_s }
        end
      end
    end
  end

  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  scope :ordered, -> { order(last_name: :asc) }

  has_many :product_orders, dependent: :destroy
  has_many :products, through: :product_orders

  validates :first_name, :last_name, :address, :phone, presence: true
  
  def full_name
    "#{first_name} #{last_name}"
  end

  def product_sum(product)
    ProductOrder.joins(:product).where(order_id: id, product_id: product.id).sum('product_orders.amount * products.price')
  end

  def product_amount(product)
    product_orders.find_by(product:).amount
  end

  def total_sum
    ProductOrder.joins(:product).where(order_id: id).sum('product_orders.amount * products.price')
  end
end

app/models/product.rb
class Product < ApplicationRecord
  scope :ordered, -> { order(name: :asc) }
  
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders
  
  validates :name, presence: true
  validates :price, :balance, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :amount, numericality: { greater_than: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :init_cart, only: :update
  
  def index
    @cart = Cart::CartManager.new(session, cart_params)
  end

  def update
    service = Cart::CartManager.new(session, params).call

    redirect_back fallback_location: root_path, notice: service
  end

  def destroy
    session.delete(:products)

    redirect_to products_path, notice: "Cart was cleaned"
  end

  private

  def cart_params
    params.permit(:id, :amount, :action_type)
  end

  def init_cart
    session[:products] = {} if session[:products].blank?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_cart, only: [:new, :create]
  attr_accessor :notice, :alert

  def show
    @order = resourse
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      service = Orders::OrderManager.new(session[:products], @order, session).call

      if service 
        flash.notice = "Order was succesfully created"
      else
        flash.alert = "Something went wrong"
      end

      redirect_to order_path(@order)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def collection
    Order.ordered
  end

  def resourse
    collection.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:first_name, :last_name, :address, :phone)
  end

  def check_cart
    redirect_to products_path if session[:products].blank?

    @session_manager = Cart::CartManager.new(session, params)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = collection
  end

  def show
    @product = resourse
  end

  private

  def collection
    Product.ordered
  end

  def resourse
    collection.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_buy_form.html.erb
<%= form_with url: add_products_to_cart_path(product), method: :patch do |f| %>
  <%= f.number_field :amount, class:'input-field w-[100px] h-[37px] inline-block', value:session.dig(:products, product.id.to_s),  min: 1 %>
  <%= f.submit "Add to cart", class:"text-white" %>
<% end %>

app/views/cart/_change_amount_form.html.erb
<%= form_with url: update_products_to_cart_path(product), method: :patch do |f| %>
  <%= f.number_field :amount, class: "input-field w-24 h-9 inline-block", value: session.dig(:products, product.id.to_s), min: 1 %>
  <%= f.submit "Change amount", class:"text-white font-medium rounded-lg px-5 py-2.5 bg-blue-700 hover: bg-blue-800 text-sm" %>
<% end %>

app/views/cart/index.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <% if @cart.get_realised_items.present? && session[:products].present? %>        %>
          <table class="min-w-full mx-4 text-sm font-light text-left">
            <thead class="font-medium border-b dark:border-neutral-500">
              <tr>
                <th scope="col" class="px-6 py-4">Name</th>
                <th scope="col" class="px-6 py-4">Price</th>
                <th scope="col" class="px-6 py-4">Amount</th>
                <th scope="col" class="px-6 py-4">Sum</th>
              </tr>
            </thead>
            <tbody>
              <% @cart.get_realised_items.each do |product| %> 
                <tr class="border-b hover:bg-neutral-100 dark:border-neutral-500 dark:hover:bg-neutral-600">
                  <td class="px-6 py-4 whitespace-nowrap"><%= product.name %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= number_to_currency(product.price, unit:"₴") %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= render "cart/change_amount_form", product: product %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= number_to_currency(@cart.product_sum(product), unit: "₴") %></td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <%= button_to remove_products_to_cart_path(product), method: :patch do %>
                        <%= image_tag "trash.svg", size: "30x30" %>
                    <% end %>
                    </td>
                  </tr>
              <% end %>
              <tr class="border-b dark:border-neutral-500">
                <td colspan="3" class="px-6 py-2 font-bold whitespace-nowrap">
                  Total sum
                </td>
                <td class="px-6 py-2 font-bold whitespace-nowrap"><%= number_to_currency(@cart.sum, unit: "₴") %></td>
              </tr>
            </tbody>
          </table>

          <div>
            <div class="inline-block m-5">
                <%= link_to 'Pay this order', new_order_path, class: "text-white bg-purple-500 font-bold rounded-lg px-5 py-2.5 ml-4 bg-amber-600 hover:bg-amber-700 text-base" %>
            </div>

            <div class="inline-block float-right m-5">
              <%= button_to 'Delete all products', cart_path(@cart), method: :delete, class: "text-white bg-gray-500 font-medium rounded-lg px-5 py-2.5 text-sm" %>
            </div>
          </div>
        <% else %>
          <div class="grid h-screen text-3xl place-items-center">Your cart is empty</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cart/show.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <% if session[:products] %>
          <table class="min-w-full mx-4 text-sm font-light text-left">
            <thead class="font-medium border-b dark:border-neutral-500">
              <tr>
                <th scope="col" class="px-6 py-4">Name</th>
                <th scope="col" class="px-6 py-4">Price</th>
                <th scope="col" class="px-6 py-4">Amount</th>
                <th scope="col" class="px-6 py-4">Sum</th>
              </tr>
            </thead>
              <tbody>
                <% @cart.items.each do |product| %>
                  <tr class="border-b hover:bg-neutral-100 dark:border-neutral-500 dark:hover:bg-neutral-600">
                    <td class="px-6 py-4 whitespace-nowrap"><%= product.name %></td>
                    <td class="px-6 py-4 whitespace-nowrap"><%= number_to_currency(product.price, :unit => "₴") %></td>
                    <td class="px-6 py-4 whitespace-nowrap"><%= render "cart/change_amount_form", product: product %></td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <%= button_to cancel_delivery_product_path(product, update_action: 'delete') do %>
                          <i class="fa fa-regular fa-trash fa-2x"></i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
                <tr class="border-b dark:border-neutral-500">
                  <td colspan="3" class="px-6 py-2 font-bold whitespace-nowrap">
                    Total sum
                  </td>
                  <td class="px-6 py-2 font-bold whitespace-nowrap"><%= number_to_currency(@cart.sum, :unit => "₴") %></td>
                </tr>
              </tbody>
          </table>

          <div>
            <div class="inline-block m-5">
                <%= link_to 'Pay this order', new_order_path, class: "text-white bg-purple-500 font-bold rounded-lg px-5 py-2.5 ml-4 bg-amber-600 hover:bg-amber-700 text-base" %>
            </div>

            <div class="inline-block float-right m-5">
              <%= button_to 'Delete all products', clean_cart_path, method: :delete, class: "text-white bg-gray-500 font-medium rounded-lg px-5 py-2.5 text-sm" %>
            </div>
          </div>
        <% else %>
            <div class="grid h-screen text-3xl place-items-center">Your cart is empty</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_messangers.html.erb
<% flash.each do |type, message| %>
  <p class="<%= type %>-flash"><%= sanitize(message) %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-violet-800 mt-8 shadow dark:bg-gray-800">
    <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
      <span class="text-sm text-white sm:text-center dark:text-gray-400">© 2023 Vlad Karabinovych.
    </span>
    <ul class="flex items-center list-reset text-xl">
        <li>
            <a href="#" class="mr-4 no-underline text-white hover:text-gray-lighter">About</a>
        </li>
        <li>
            <a href="#" class="mr-4 no-underline text-white hover:text-gray-lighter">Privacy Policy</a>
        </li>
        <li>
            <a href="#" class="mr-4 no-underline text-white hover:text-gray-lighter">Licensing</a>
        </li>
        <li>
            <a href="#" class="mr-4 no-underline text-white hover:text-gray-lighter">Contact</a>
        </li>
    </ul>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-violet-800 mb-8 text-white py-6">
  <div class="container flex items-center justify-between mx-auto px-4">
    <h1 class="text-2xl">Logo</h1>
    <ul class="flex items-center list-reset text-xl">
      <li class="px-4">
       <%= link_to 'Products', products_path, class: "nav-item" %>
      </li>
      <li>
        <%= link_to cart_index_path do %>
          <%= image_tag "cart.svg", size: "30x30" %>
        <% end %>
      </li>
    </ul> 
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-screen">
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messangers' %>

    <div class="flex-grow">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, class: "contents") do |f| %>
  <div class="my-5">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "block shadow rounded-md…" %>
  </div>

  <div class="my-5">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "block shadow rounded-md…" %>
  </div>

  <div class="my-5">
    <%= f.label :address %>
    <%= f.text_area :address, class: "block shadow rounded-md…" %>
  </div>
  
  <div class="my-5">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "block shadow rounded-md…" %>
  </div>
  
  <div class="inline">
    <%= f.submit class: "text-white bg-teal-400 font-medium rounded-lg px-5 py-2.5 text-sm" %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div class="min-w-fit rounded-lg shadow-lg m-4 p-6 bg-purple-950 flex flex-col justify-between">
  <dl class="min-w-full text-white bg-purple-950 divide-y divide-gray-700">
  <div class="block block-shadow p-6">
    <ul class="ms-6 w-96">
      <h1 class="font-bold text-3xl mb-5">Order №<%= order.id %></h1>
      <li class="mb-4"><%= order.full_name %></li>
      <li class="mb-4"><%= order.address %></li>
      <li class="mb-4"><%= order.phone %></li>
    </ul>
    <table class="min-w-full text-left text-sm font-light">
      <thead class="border-b font-medium dark:border-neutral-500 text-left">
        <tr>
          <th scope="col" class="pe-6 py-4">Title</th>
          <th scope="col" class="pe-6 py-4">Price</th>
          <th scope="col" class="pe-6 py-4">Amount</th>
          <th scope="col" class="pe-6 py-4">Sum</th>
        </tr>
      </thead>

      <tbody>
        <% order.products.each do |product| %>
          <tr class="border-b">
            <td class="cart-item"><%= product.name %></td>
            <td class="cart-item"><%= number_to_currency(product.price, unit: "₴ ") %></td>
            <td class="cart-item"><%= order.product_amount(product) %></td>
            <td class="cart-item"><%= number_to_currency(order.product_sum(product), unit: "₴ ") %></td>
          </tr>
        <% end %>
        <tr class="border-b">
          <td colspan="3" class="whitespace-nowrap font-medium pe-11 py-2 text-right">
            Total sum
          </td>
          <td class="whitespace-nowrap pe-6 py-2"><%= number_to_currency(order.total_sum, unit: "₴ ") %></td>
        </tr>
      </tbody>
    </table>
    <div class="flex justify-between pt-5">
      <%= link_to "Show this order", order, class: "text-white bg-violet-800 font-medium rounded-lg px-5 py-2.5 text-sm" %>
      <%= link_to 'Edit this order', edit_order_path(order), class: "text-white bg-teal-400 font-medium rounded-lg px-5 py-2.5 text-sm" %>
      <%= link_to 'Back to products', products_path, class: "text-white bg-gray-500 font-medium rounded-lg px-5 py-2.5 text-sm" %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container mx-auto flex-wrap">
    <h2 class="text-gray-900 my-4 text- font-sans text-center font-bold text-4xl">
    All Orders
    </h2>
    <div class="flex flex-wrap justify-center">
     <%= render @order %>
    </div>
</div>

app/views/orders/new.html.erb
<div class="container p-4">
  <h2 class="text-gray-900 mb-4 text- font-sans text-center font-bold text-4xl">
    New Order
  </h2>
  <%= render "form", order: @order %>

    <%= link_to 'Back to cart', cart_index_path, class: "text-white bg-gray-500 font-medium rounded-lg px-5 py-2.5 text-sm" %>
</div>

app/views/orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <div class="flex flex-col text-base sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">

        <div class="block block-shadow p-6">
          <ul class="ms-6 w-96">
            <h1 class="font-bold text-3xl mb-5">Order №<%= @order.id %></h1>
            <li class="mb-4"><%= @order.full_name %></li>
            <li class="mb-4"><%= @order.address %></li>
            <li class="mb-4"><%= @order.phone %></li>
          </ul>
          <table class="min-w-full text-left text-sm font-light">
            <thead class="border-b font-medium dark:border-neutral-500 text-left">
              <tr>
                <th scope="col" class="pe-6 py-4">Title</th>
                <th scope="col" class="pe-6 py-4">Price</th>
                <th scope="col" class="pe-6 py-4">Amount</th>
                <th scope="col" class="pe-6 py-4">Sum</th>
              </tr>
            </thead>

            <tbody>
              <% @order.products.each do |product| %>
                <tr class="border-b">
                  <td class="cart-item"><%= product.name %></td>
                  <td class="cart-item"><%= number_to_currency(product.price, unit: "₴ ") %></td>
                  <td class="cart-item"><%= @order.product_amount(product) %></td>
                  <td class="cart-item"><%= number_to_currency(@order.product_sum(product), unit: "₴ ") %></td>
                </tr>
              <% end %>
              <tr class="border-b">
                <td colspan="3" class="whitespace-nowrap font-medium pe-11 py-2 text-right">
                  Total sum
                </td>
                <td class="whitespace-nowrap pe-6 py-2"><%= number_to_currency(@order.total_sum, unit: "₴ ") %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="inline-block ml-2">
      <%= link_to 'Back to products', products_path, class: "text-white bg-gray-500 font-medium rounded-lg px-5 py-2.5 text-sm" %>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div class="flex w-1/4 flex-wrap">
  <div class="w-full p-1 md:p-2">
    <div class="bg-violet-400 text-white p-4" id="<%= dom_id product %>">
      <div class="grid gap-4 grid-cols-1">
        <div class="font-semibold text-3xl truncate ...">
          <%= product.name %>
        </div>

        <div class="truncate ...">
          <%= product.description %>
        </div>

        <div>
          Price: <%= number_to_currency(product.price, precision: 2, unit:"₴") %>
        </div>

        <div>
          Available: <%= product.balance %>
        </div>
      </div>

      <div class="flex justify-between pt-5">
        <%= link_to "Show this product", product, class: "text-white bg-violet-800 font-medium rounded-lg px-5 py-2.5 text-sm" %>
      </div>
      <hr class="mt-6">

      <div class="relative mb-3 text-black">
        <% if product.balance.positive? %>
          <%= render "cart/buy_form", product: product %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="min-h-full">
  <div class="flex justify-between items-center pb-8">
    <h1 class="mx-auto text-lg font-bold text-4xl">Products</h1>
  </div>

  <table id="products" class="mx-auto">
    <tbody>
      <div class="container mx-auto px-5 py-2">
        <div class="-m-1 flex flex-wrap md:-m-2">
          <%= render @products %>
        </div>
      </div>
    </tbody>
  </table>
</div>

app/views/products/show.html.erb
<div class="mx-auto">
  <div class="w-full p-1 md:p-2 m-5">
    <div class="grid gap-4 grid-cols-1">
      <div class="font-semibold text-3xl text-center">
        <%= @product.name %>
      </div>

      <div>
        <%= @product.description %> 
      </div>

      <div>
        Price: <%= number_to_currency(@product.price, precision: 2, unit:"₴") %>
      </div>

      <div>
        Available: <%= @product.balance %>
      </div>
    </div>

    <div class="relative mb-3">
      <% if @product.balance.positive? %>
        <%= render "cart/buy_form", product: @product %>
      <% end %>
    </div>

    <div class="inline-block ml-2">
      <%= link_to 'Back to products', products_path, class: "text-white bg-gray-500 font-medium rounded-lg px-5 py-2.5 text-sm" %>
    </div>

  </div>
</div>